.eslintrc, examples/demos/basic.js, package.json, src/Calendar.js, src/Month.js, src/less/month.less, yarn.lock
This PR adds the ability to render all the events in the calendar when passing down the `showAllEvents` prop to calendar. Additional changes made were to the eslint and the code formatting. Prettier was added to provide more consistent code formatting.
=> Show All Events in Calendar

package.json, yarn.lock
Summary: Add eslint-config-prettier to fix failing build
=> Add eslint-config-prettier

package.json
Summary: The files array for this package haf lib, instead of src, as the root dir. This was updated.
=> Fix files array

package.json
Changed back a few things and added a prepublish hook so I don't forget to build.
=> Fix Build Error

examples/demos/dnd.js, package.json, src/EventCell.js, src/less/styles.less, stories/Calendar.js, test/visual-test.html, webpack/visual-test.js, yarn.lock
This PR deals with cleaning up the repo a little and fixing bugs.
=> Clean up and fix bugs

package.json, src/addons/dragAndDrop/backgroundWrapper.js
This PR deals with fixing the resizing not working. This was due to the fact that I was not using the start|endAccessor to access the values for the start and end time. Now that I am, it should work as expected.
=> Fix resizing issue

src/Month.js, src/addons/dragAndDrop/backgroundWrapper.js
This PR provides a fix for handling accommodating all events and the resize functionality.
=> Fix for accommodate all events and resize

package.json, src/addons/dragAndDrop/ResizableMonthEvent.js, src/addons/dragAndDrop/styles.less, src/less/event.less, yarn.lock
This PR updates the anchors on the left and right of the resizable event to be closer to the edge.
=> Resize anchors

src/addons/dragAndDrop/backgroundWrapper.js, src/addons/dragAndDrop/index.js
Add onOutsideEventDrop prop so that the calendar knows how to handle outside event drops properly.
=> Add onOutsideEventDrop Action

package.json, src/addons/dragAndDrop/__tests__/helpers.spec.js, src/addons/dragAndDrop/backgroundWrapper.js, src/addons/dragAndDrop/helpers.js, yarn.lock
This PR updates the merge function being utilized in the addons dnd section of the library. It was not working consistently and therefore I updated how this current function works in dnd. I did not try and replace the merge function that is being used in other places of the app but this may happen at some point.
=> Fix Merge function

src/addons/dragAndDrop/backgroundWrapper.js
This is a quick fix to remove the invalid date that is being returned when dragging and dropping.
=> Fix add milliseconds

examples/App.js, examples/demos/dnd.js, src/BackgroundCells.js, src/Calendar.js, src/DateContentRow.js, src/EventCell.js, src/EventRowMixin.js, src/Month.js, src/Selection.js
This PR adds the feature of a right click context menu when hovered over an event.
=> Add Context Menu for Right Click on Event

src/EventCell.js
This properly sets styles via styled component.
=> EventCell style fixes

src/addons/dragAndDrop/__tests__/helpers.spec.js
This is a temporary fix so that I can deploy a new version of RBC.
=> Remove Tests

src/EventRowMixin.js
Pass user event data to `isSelected` instead of internal wrapper.
=> Fix selected in EventCell

src/BackgroundCells.js
Elevating the div around the cellWrapper so that it's index rises above when dropping an element on the calendar.
=> Drag and drop event onto day cell

src/BackgroundCells.js
Reverts citrusbyte/react-big-calendar#32
=> Revert "Drag and drop event onto day cell"

src/addons/dragAndDrop/index.js, src/addons/dragAndDrop/styles.less
This PR is to *actually* fix the the drag and drop resize functionality. The user now should be able to update the event on resize and be able to drop the event anywhere on the calendar date.
=> Fix Drag and Drop Resizing

examples/demos/dnd.js, examples/events.js, package.json, src/addons/dragAndDrop/backgroundWrapper.js, src/addons/dragAndDrop/itemTypes.js, yarn.lock
This PR adds the ability to resize the event on hover so that the user can see the changes live.
=> Add resize on hover feature

src/addons/dragAndDrop/DateContentRowWrapper.js, src/addons/dragAndDrop/DraggableEventWrapper.js, src/addons/dragAndDrop/backgroundWrapper.js
In order to get master into a working state I am doing to revert this merge. These fixes introduced some bugs and made the calendar not workable.
=> Revert "Drag drop reorder"

examples/demos/dnd.js, src/addons/dragAndDrop/backgroundWrapper.js
This PR allows the user to see where the event will be dropped before it's dropped.
=> Allow live drop

examples/demos/dnd.js, src/addons/dragAndDrop/backgroundWrapper.js
This PR fixes the date format errors and also the dnd example which was temporarily broken. This PR is intended to fix the disappearing event issue in `itv-calendar`.
https://github.com/citrusbyte/itv-calendar/issues/177
=> Fix Errors

src/EventCell.js
This PR fixes the selection of an event issue. The main problem was using `onBlur` which should be a non-issue now that it is resolved in another `itv-calendar` issue of the same branch. By removing `onBlur` I am getting rid of the flicker that occured when an event was selected.
=> Fix selection bug

src/BackgroundCells.js, src/DateContentRow.js
Reverts citrusbyte/react-big-calendar#55
=> Revert "Deselect event when background cell is selected"

src/Calendar.js
This PR fixes deselecting an event the right way.
=> Fix deselect the right way

src/Calendar.js
This PR is a hotfix to remove the bug related to selecting an event.
=> Fix select event bug

src/addons/dragAndDrop/DraggableEventWrapper.js
If an event is locked it's disabled from being dragged.
=> Disable dnd on locked event

src/Calendar.js
Render two month view based on prop passed to calendar.
=> Render two month view

src/Calendar.js
ITV wants events to render on both months after all.
=> Show events on both months

src/Calendar.js
=> Adjust month header label when hovered over month two
