- examples/demos/dnd.js
- package.json
- src/Calendar.js
- src/DateContentRow.js
- src/EventCell.js
- src/EventRowMixin.js
- src/Month.js
- src/addons/dragAndDrop/ResizableMonthEvent.js
- src/addons/dragAndDrop/backgroundWrapper.js
- src/addons/dragAndDrop/compose.js
- src/addons/dragAndDrop/index.js
- src/addons/dragAndDrop/styles.less
- yarn.lock
This PR adds the ability to resize month events by clicking and dragging on the ends of an event.
Other code formatting changes were made with the help of prettier.
> Resize Month Events

- examples/demos/basic.js
- examples/demos/dnd.js
- examples/demos/selectable.js
- package.json
- src/Calendar.js
- src/DateContentRow.js
- src/EventCell.js
- src/EventRowMixin.js
- src/Month.js
This PR adds the ability to rename the event title inline in the calendar when the event title is double clicked. The event title goes back to its normal state after an enter or blur action.
> Add rename-events-inline feature

- src/Calendar.js
- src/Toolbar.js
- stories/Calendar.js
This PR adds support for adding a custom element on the toolbar via the new `toolbarExtras` prop.
> Add toolbar extras capability

- src/EventCell.js
Summary: The onBlur action would not kick off a change when updating an event name inline. This is now fixed. Also the caret moves to the end of the input on focus.
> Fix onBlur Bug

- package.json
- src/EventCell.js
- yarn.lock
Summary: Using Rambda is failing the CRA production build because rambda fails to minify:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify.
This is based on this build:
https://circleci.com/gh/citrusbyte/itv-calendar/543
> Remove Rambda, Add Ramda

- examples/demos/dnd.js
- src/Calendar.js
- src/Month.js
We would like to allow the user access to how items are listed in a given `DateContentRow` and to do so we must expose the sort func via a prop.
> Expose sort func via Cal prop

- examples/demos/dnd.js
- src/Calendar.js
- src/ContextMenuTypes.js
- src/DateContentRow.js
- src/EventCell.js
- src/EventRowMixin.js
- src/Month.js
- src/addons/dragAndDrop/index.js
This PR abstracts away components for ContextMenu and ResizableMonthEvent. The reason for this is so that itv-calendar itself has the control over what gets rendered and not react-big-calendar. This will make it easier to make changes to these components in the future instead of having to come back here and make those changes to the component. Ideally, we really should only be making changes to the functionality of the calendar and not how something looks. That should instead all be within itv-calendar.
> Abstract Away Components for ContextMenu and ResizableMonthEvent

- examples/demos/dnd.js
- examples/events.js
- src/DateContentRow.js
- src/addons/dragAndDrop/DateContentRowWrapper.js
When we attempt to reorder segments vertically that have variable length in the same week row we would get bizarre rendering issues and would experience performance issues because segment position was being miscalculated.
The naive reduce algo used introduced a lot of complexity because of `levels`. I was attempting to reduce `levels` to an array of `segments` that only lived in the DayCell I was hovering in. For example:
If I was hovering over the ninth, the reduced `levels` array would only contain 2 segments. This introduced a lot of edge cases when segments that started on earlier days and overflowed onto the day-cell I was hovering in. To solve this, instead of reducing the `levels` array to a list of segments, I reduced it to a list of `levels` with a single `segment` object... A …
> Fix vertical order

- package.json
- src/addons/dragAndDrop/styles.less
- yarn.lock
This PR fixes the issue where a user would have to "find" a place to drop an event when resizing it. Now the user can just drop the event on any day cell and it will resize.
> Resize Event to be Smaller

- src/EventCell.js
Hopefully this is the last issue of this kind. The regression came after I introduced the data wrapper:
```
event = { data: userEventObjHere, ... };
```
internally we call the entire obj `event` but the user facing/assignable obj can be accessed via `event.data`.
> Bad event user data accessor

- src/addons/dragAndDrop/backgroundWrapper.js
I overlooked this when I copy/pasted some code. The eventType should be hover and not drop.
> Declare hover event as type hover

- src/EventCell.js
This PR fixes a bug where when a user clicked to edit an event title inline, it would not show the correct event title but rather a title from another event. This was due to the fact that the state was not updated in `componentWillReceiveProps`.
> Fix inline edit bug

- src/addons/dragAndDrop/backgroundWrapper.js
This PR fixes errors when dnd from sidebar to calendar occurs. It makes more declarative the type of event that occurs when the user is dragging an event on the calendar to make the distinction between a drop and hover event.
> Fix drag and drop from sidebar issues

- src/addons/dragAndDrop/DateContentRowWrapper.js
This PR fixes errors that occurred when trying to reorder events from the sidebar. This does not effect vertical reordering when events exist in the calendar. This will allow us to continue to push and update to this repo without an hassle.
> Revert errors that occurred when reordering from sidebar

- src/EventCell.js
This is a hot fix that I thought was previously implemented but was not. Essentially I am increasing the `setTimeout` to 200ms to prevent event clobbering that is effecting the right-clicking of events.
> Fix event clobbering

- src/EventRow.js
- src/Month.js
- src/addons/dragAndDrop/DateContentRowWrapper.js
- src/addons/dragAndDrop/DraggableEventWrapper.js
- src/addons/dragAndDrop/backgroundWrapper.js
- src/addons/dragAndDrop/eventLevels.js
- src/addons/dragAndDrop/index.js
This introduces main logic for vertical + horizontal reorder. However since a few issues persist regarding reordering between days and weeks we are restricting reorder to the day we start dragging from. If we drag into another day, this action will reset vertical reorder and not allow reordering until the item is dropped.
> Vertical reorder fixes

- src/addons/dragAndDrop/DraggableEventWrapper.js
This PR fixes the bug that did not allow the user to select the event name when editing inline.
<a href="https://cl.ly/3W0l2F2R240P" target="_blank"><img src="https://d1ax1i5f2y3x71.cloudfront.net/items/2M3m0d230S173F0m1h1l/Screen%20Recording%202017-11-30%20at%2009.24%20AM.gif" style="display: block;height: auto;width: 100%;"/></a>
https://github.com/citrusbyte/itv-calendar/issues/187
> Fix ability to select event name when editing inline

- src/addons/dragAndDrop/DraggableEventWrapper.js
This PR fixes the inline select event name bug for real this time. I should have done an integration test to make sure the previous PR was working properly. I found out that the path to a component's state is different in React 16 so that is why the previous solution did not work. And now `citrusbyte-calendar` needs to be aware of these differences which is unfortunate.
> Fix inline select event name

- src/utils/eventLevels.js
Instead of using a forward loop to generate `levels`, we now backtrack in order to figure out the adequate level a segment should live in.
> Improve levels preprocessing

- src/BackgroundCells.js
- src/DateContentRow.js
This PR is a quick fix to deselect an event when a background cell is selected. There was an attempt in the past to handle this with `onBlur` but that did not work as expected because the bubbling of events made it difficult to implement. This is a quick fix to deselect an event when a background cell is selected.
> Deselect event when background cell is selected

- src/addons/dragAndDrop/eventLevels.js
Fixes two issues:
- under certain conditions the position would be miscalculated; this was a result of previous changes I made.
- under certain circumstances, the overlapping segments were not grouped currently due to naive approach to collectively calculate the range of a level and use that as range. Where the best approach is to check each segment and see if each overlap and group that way, or in other words intersect 2 arrays of segments for overlapping segs.
> Fix bad seg pos

- src/addons/dragAndDrop/DateContentRowWrapper.js
Ensure `ancestors` prop is added to event item when it is being created.
> Fix missing ancestors

- src/addons/dragAndDrop/DraggableEventWrapper.js
- src/addons/dragAndDrop/index.js
This PR adds the `onOutsideEventOrderAndDrop` function to the `DraggableEventWrapper` in order to perform a side-effect after dropping an `outsideEvent` on the calendar. This is specifically to update parent categories visibility in itv-calendar.
> Pass down handler for event drop side-effects
